name: flweather
description: "Flutter weather app."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  location: ^8.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

#  fonts:
#    - family: FONTFAMILYNAME
#      fonts:
#        - asset: assets/fonts/ADDFONTNAMEHERE.ttf
#          weight: FONTWEIGHT